// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Dracula",
    url: "assets/dracula.jpg",
    originalPrice: 20.00,
    salePrice: 11.99,
    rating: 4.5,
  },
  {
    id: 2,
    title: "This Thing Between Us",
    url: "assets/this-thing-between-us.jpg",
    originalPrice: 10.99,
    salePrice: null,
    rating: 4,
  },
  {
    id: 3,
    title: "The Haunting of Hill House",
    url: "assets/haunting-hill-house.jpg",
    originalPrice: 26.99,
    salePrice: 15.99,
    rating: 3.5,
  },
  {
    id: 4,
    title: "PenPal",
    url: "assets/penpal.jpg",
    originalPrice: 12.99,
    salePrice: 8.99,
    rating: 4.8,
  },
  {
    id: 5,
    title: "Pet Sematary",
    url: "assets/pet-sematary.jpg",
    originalPrice: 27.99,
    salePrice: 16.99,
    rating: 4.5,
  },
  {
    id: 6,
    title: "Seed",
    url: "assets/seed.jpg",
    originalPrice: 14.95,
    salePrice: 9.95,
    rating: 5,
  },
  {
    id: 7,
    title: "Stolen Tongues",
    url: "assets/stolen-tongues.jpg",
    originalPrice: 19.99,
    salePrice: null,
    rating: 4,
  },
  {
    id: 8,
    title: "Incidents Around the House",
    url: "assets/incidents-around-the-house.jpg",
    originalPrice: 20.00,
    salePrice: 18.49,
    rating: 4.5,
  },
  {
    id: 9,
    title: "Fire In The Sky",
    url: "assets/travis-walton.jpg",
    originalPrice: 16.99,
    salePrice: null,
    rating: 3.5,
  },
  {
    id: 10,
    title: "Bird Box",
    url: "assets/bird-box.jpg",
    originalPrice: 25.99,
    salePrice: 14.95,
    rating: 4,
  },
  {
    id: 11,
    title: "Mary: A Novel",
    url: "assets/mary.jpg",
    originalPrice: 16.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 12,
    title: "Ring Shout",
    url: "assets/ring-shout.jpg",
    originalPrice: 19.99,
    salePrice: 13.99,
    rating: 4.5,
  },
];